#!/bin/sh

while :; do
	. ~/.sway/status_vars

	sep=' | '
	[ "$VPN" ] && VPN=🔒 || VPN=🔓❌
	[ "$NET" ] && NET=📶 || NET=❌

	printf '%s\n' "${NET} ${sep} ${VPN:-} ${sep} 🔉 ${AUDIO} ${sep} CPU: ${CPU_PCNT}% ${sep} RAM: ${RAM}% ${sep} ${DATE} "
done
