#!/bin/sh

battery_info=$(acpi -b | awk '{printf "%d%% (%s %s %s)", $4, $3, $5, $6}')

date=$(date +'%a, %b %-d %-I:%M %p')

# Seperator
sep='  |  '

printf '%s' "BATTERY: ${battery_info} ${sep} ${date}"
