#!/usr/bin/make -f
# Usually used like: ./Makefile.guided -B

SELF_DESC=Self-guided.

LGC_DESC=Luma-guided-chroma denoising.
LGC=I=SHARE_LUMA:HOOKS=CHROMA:MEANI=1.125:E=0.005

FAST_DESC=Fast.
FAST=IP=2

ANIME_DESC=Tuned for anime.
ANIME=PREI=2.0

all: ../guided_s_fast.glsl ../guided_lgc.glsl ../guided_anime.glsl

../guided_s_fast.glsl: ../guided_s.glsl
	env GUIDED_DESC="$(SELF_DESC) $(FAST_DESC)" GUIDED_OPTS="$(FAST)" ./guided_cfg < $? > $@
../guided_lgc.glsl: ../guided.glsl
	env GUIDED_DESC="$(LGC_DESC)" GUIDED_OPTS="$(LGC)" ./guided_cfg < $? > $@
../guided_anime.glsl: ../guided.glsl
	env GUIDED_DESC="$(ANIME_DESC)" GUIDED_OPTS="$(ANIME)" ./guided_cfg < $? > $@

