#!/usr/bin/make -f
# Usually used like: ./Makefile.nlm -B

NO_ROTATE=RI=0:RFI=0

LQ_DESC=Faster, but lower quality.
LQ_LUMA=S=1.25:R=3:WD=1:$(NO_ROTATE)
LQ=WD=1:RF_LUMA=PRE1.25/

HQ_DESC=Slow, but higher quality.
HQ_LUMA=S=2.25:P=4:PS=6:$(NO_ROTATE):ASP=1:RF_LUMA=../nlmeans.glsl
HQ=

HEAVY_DESC=Tuned for heavy noise.
HEAVY=SW=EPSILON:EP=0

MEDIUM_DESC=Tuned for medium noise.
MEDIUM=SW=0.5:$(HEAVY)

HQX_DESC=Very slow, should offer the best quality.
HQX_LUMA=P=5:$(HQ_LUMA)
HQX=P=5:$(HQ)

TEMPORAL_DESC=Very experimental and buggy, limited to vo=gpu-next.
TEMPORAL=T_FRAME_LIMIT=2:T_RES=1920x1080
TEMPORAL_LUMA=T=2:WD=1:$(NO_ROTATE)

TEMPORAL_SHARPEN_DENOISE_DESC=$(TEMPORAL_DESC) $(SHARPEN_DENOISE_DESC)
TEMPORAL_SHARPEN_DENOISE_LUMA=ASP=1:$(TEMPORAL_LUMA)
TEMPORAL_SHARPEN_DENOISE=$(TEMPORAL):$(SHARPEN_DENOISE)

SHARPEN_ONLY_DESC=Sharpen without denoising.
SHARPEN_ONLY=AS=2

SHARPEN_DENOISE_DESC=Sharpen and denoise.
SHARPEN_DENOISE=AS=1

2X_DESC=Experimental upscaler
2X=CFG_HOOKS=LUMA:CFG_SIZE=2*:S=1.5:RF_LUMA=../FSRCNNX_x2_8-0-4-1.glsl:RF=0:SF=2:$(MEDIUM):EP=0

LGC_DESC=Experimental luma-guided chroma denoising, kinda similar to KrigBilateral
LGC=CFG_HOOKS=CHROMA:CFG_SIZE=LUMA:RF=SHARE_LUMA:RF_LUMA=0:EP=0:D1W=1:S=11.66:WD=0:SW=0.75:RI=3:RFI=2

all: ../nlmeans.glsl ../nlmeans_lgc.glsl ../nlmeans_2x.glsl ../nlmeans_heavy.glsl ../nlmeans_medium.glsl ../nlmeans_temporal.glsl ../nlmeans_hq.glsl ../nlmeans_hq_heavy.glsl ../nlmeans_hq_medium.glsl ../nlmeans_hqx.glsl ../nlmeans_lq.glsl ../nlmeans_sharpen_denoise.glsl ../nlmeans_temporal_sharpen_denoise.glsl ../nlmeans_hq_sharpen_denoise.glsl ../nlmeans_sharpen_only.glsl

../nlmeans.glsl: nlmeans_template
	./shader_cfg $? > $@
../nlmeans_lgc.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(LGC_DESC)" OPTS="$(LGC)" $? > $@
../nlmeans_2x.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(2X_DESC)" OPTS="$(2X)" $? > $@
../nlmeans_heavy.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(HEAVY_DESC)" OPTS="$(HEAVY)" $? > $@
../nlmeans_medium.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(MEDIUM_DESC)" OPTS="$(MEDIUM)" $? > $@
../nlmeans_temporal.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(TEMPORAL_DESC)" OPTS="$(TEMPORAL)" OPTS_LUMA="$(TEMPORAL_LUMA)" $? > $@
../nlmeans_hq.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(HQ_DESC)" OPTS="$(HQ)" OPTS_LUMA="$(HQ_LUMA)" $? > $@
../nlmeans_hq_heavy.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(HQ_DESC) $(HEAVY_DESC)" OPTS="$(HEAVY):$(HQ)" OPTS_LUMA="$(HEAVY):$(HQ_LUMA)" $? > $@
../nlmeans_hq_medium.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(HQ_DESC) $(MEDIUM_DESC)" OPTS="$(MEDIUM):$(HQ)" OPTS_LUMA="$(MEDIUM):$(HQ_LUMA)" $? > $@
../nlmeans_hqx.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(HQX_DESC)" OPTS="$(HQX)" OPTS_LUMA="$(HQX_LUMA)" $? > $@
../nlmeans_lq.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(LQ_DESC)" OPTS="$(LQ)" OPTS_LUMA="$(LQ_LUMA)" $? > $@
../nlmeans_sharpen_denoise.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(SHARPEN_DENOISE_DESC)" OPTS="$(SHARPEN_DENOISE)" OPTS_LUMA="$(SHARPEN_DENOISE)" $? > $@
../nlmeans_temporal_sharpen_denoise.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(TEMPORAL_SHARPEN_DENOISE_DESC)" OPTS="$(TEMPORAL_SHARPEN_DENOISE)" OPTS_LUMA="$(TEMPORAL_SHARPEN_DENOISE_LUMA)" $? > $@
../nlmeans_hq_sharpen_denoise.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(HQ_DESC) $(SHARPEN_DENOISE_DESC)" OPTS="$(SHARPEN_DENOISE):$(HQ)" OPTS_LUMA="$(SHARPEN_DENOISE):$(HQ_LUMA)" $? > $@
../nlmeans_sharpen_only.glsl: nlmeans_template
	./shader_cfg DESC="$@: $(SHARPEN_ONLY_DESC)" OPTS="$(SHARPEN_ONLY)" OPTS_LUMA="$(SHARPEN_ONLY)" $? > $@

