#!/bin/sh -e
# Downloads YouTube videos with youtube-dl into ~/youtube/
#
# Also consider checking out this script for converting YouTube links
# into RSS feeds https://github.com/AN3223/scripts/blob/master/y2rss

[ ! "$LINK" ] && exit
mkdir -p "$HOME/youtube"

youtube-dl -q --no-warnings -o "$HOME/youtube/%(uploader)s - %(title)s.%(ext)s" "$LINK"

